---
default:
  run_id: 'unet_sigmoid_nearest_extra_dssim'
  restart: false
  model: 'unet'
training:
  directory:
    training_hires:    /home/dryglicki/data/sentinel-2/paired/training/red
    training_lowres:   /home/dryglicki/data/sentinel-2/paired/training/nirLow
    truth_train:       /home/dryglicki/data/sentinel-2/paired/training/nirHigh
    validation_hires:  /home/dryglicki/data/sentinel-2/paired/validation/red
    validation_lowres: /home/dryglicki/data/sentinel-2/paired/validation/nirLow
    truth_valid:       /home/dryglicki/data/sentinel-2/paired/validation/nirHigh
  dataset:
    batch_size: 48
    shuffle_size: 96
  fit:
    epochs: 200
    steps_per_epoch:
    validation_steps: 8
    patience: 10
  model:
    scaling_factor: 4
    filter_size: 128
    num_blocks: 6
    interpolation: 'nearest'
    unet_filter_sizes:
      - 32
      - 64
      - 128
      - 256
      - 512
      - 1024
    classic: false
    add_batchnorm: true
    final_layer: 'extra'
    activation_final: 'sigmoid'
  optimizer:
    name: 'adam'
    initial_lr: 2.0e-4
    final_lr: 1.0e-5
    beta_1: 0.90
    beta_2: 0.999
    epsilon: 1.0e-7
