---
default:
  run_id: 'firewx-dsen2_mae_and_dssim'
  restart: false
  model: 'dsen2'
training:
  restart:
    path: /home/dryglicki/code/DSen2/training/firewx-unet_mae/best_checkpoints/best-min_val_loss-epoch_0200.hdf5
    epoch: 200
  directory:
    training_hires:    /home/dryglicki/data/sentinel-2/paired/training/red
    training_lowres:   /home/dryglicki/data/sentinel-2/paired/training/nirLow
    truth_train:       /home/dryglicki/data/sentinel-2/paired/training/nirHigh
    validation_hires:  /home/dryglicki/data/sentinel-2/paired/validation/red
    validation_lowres: /home/dryglicki/data/sentinel-2/paired/validation/nirLow
    truth_valid:       /home/dryglicki/data/sentinel-2/paired/validation/nirHigh
  dataset:
    batch_size: 48
    shuffle_size: 64
    augment: true
  glob:
    training_hires:    '*.png'
    training_lowres:   '*.png'
    truth_train:       '*.png'
    validation_hires:  '*.png'
    validation_lowres: '*.png'
    truth_valid:       '*.png'
  fit:
    epochs: 200
    steps_per_epoch:
    validation_steps: 100
    patience: 10
    weight_dssim: 0.25
  model:
    scaling_factor: 4
    filter_size: 64
    num_blocks: 12
    interpolation: 'nearest'
    scaling: 0.1
    unet_filter_sizes:
      - 32
      - 64
      - 128
      - 256
      - 512
      - 1024
    classic: true
    add_batchnorm: false
    final_layer: 'extra'
    activation_final: 'sigmoid'
    upsample: 'shuffle'
    initializer: 'random_truncated'
  optimizer:
    name: 'adam'
    initial_lr: 1.0e-4
    final_lr: 1.0e-5
    beta_1: 0.90
    beta_2: 0.999
    epsilon: 1.0e-7
inference:
  dataset:
    batch_size: 2
  directory:
    test_hires:  /home/dryglicki/data/sentinel-2/paired/testing/red
    test_lowres: /home/dryglicki/data/sentinel-2/paired/testing/nirLow
    test_valid:       /home/dryglicki/data/sentinel-2/paired/testing/nirHigh
    output: /home/dryglicki/data/sentinel-2/paired/inference/output
  glob:
    test_hires:  '*.png'
    test_lowres: '*.png'
    truth_test:  '*.png'
